// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SISTrainingRestAPI.Models;

#nullable disable

namespace SISTrainingRestAPI.Migrations
{
    [DbContext(typeof(SistrainingContext))]
    [Migration("20231214102953_EmployeeTableAdded")]
    partial class EmployeeTableAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SISTrainingRestAPI.Models.TrainingStaff", b =>
                {
                    b.Property<long>("StaffId")
                        .HasColumnType("bigint");

                    b.Property<string>("Course")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("StaffName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("StaffId")
                        .HasName("PK__Training__96D4AB179EE11918");

                    b.ToTable("TrainingStaff", (string)null);
                });

            modelBuilder.Entity("SISTrainingRestAPI.Models.TrainingStudent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.Property<long?>("StaffId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Training__3214EC0713D5E96B");

                    b.HasIndex("StaffId");

                    b.ToTable("TrainingStudents");
                });

            modelBuilder.Entity("SISTrainingRestAPI.Models.TrainingStudent", b =>
                {
                    b.HasOne("SISTrainingRestAPI.Models.TrainingStaff", "Staff")
                        .WithMany("TrainingStudents")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK__TrainingS__Staff__4F7CD00D");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("SISTrainingRestAPI.Models.TrainingStaff", b =>
                {
                    b.Navigation("TrainingStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
